# Generated by Django 5.0.2 on 2024-02-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['puzzle', 'order']},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ('identifier',)},
        ),
        migrations.AddIndex(
            model_name='hint',
            index=models.Index(fields=['puzzle', 'order'], name='puzzles_hin_puzzle__f344cd_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['identifier'], name='puzzles_puz_identif_0c544c_idx'),
        ),
    ]
