# Generated by Django 5.0.2 on 2024-02-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_alter_hint_options_alter_puzzle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.puzzle'),
        ),
    ]
