# Generated by Django 5.0.2 on 2024-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_alter_puzzle_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='password_type',
            field=models.CharField(choices=[('letters', 'letters'), ('numbers', 'numbers')], default='letters', max_length=10),
            preserve_default=False,
        ),
    ]
