# Generated by Django 5.0.2 on 2024-02-28 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_solves'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solves',
            new_name='Solve',
        ),
    ]
