# Generated by Django 5.0.2 on 2024-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_alter_solve_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='password_type',
            field=models.CharField(choices=[('text', 'Letters'), ('number', 'Numbers')], max_length=10),
        ),
    ]
